import os
from datetime import datetime

REPORTS_DIR = "docs"
index_file_path = os.path.join(REPORTS_DIR, "index.html")

entries = [
    d for d in os.listdir(REPORTS_DIR)
    if os.path.isdir(os.path.join(REPORTS_DIR, d)) and d.startswith("202")
]
entries.sort(reverse=True)

html = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Allure Report Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; }
        .container { max-width: 720px; }
        .report-link:hover { background-color: #e2e6ea; }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4 text-center">
            <img src="https://cdn-icons-png.flaticon.com/512/2991/2991148.png" width="40" class="me-2">
            Available Test Reports
        </h1>
        <ul class="list-group">
"""

for i, entry in enumerate(entries):
    dt = datetime.strptime(entry, "%Y%m%d_%H%M%S")
    pretty_time = dt.strftime("%Y-%m-%d %H:%M")
    badge = ' <span class="badge bg-success">Latest</span>' if i == 0 else ""
    html += f'''  <li class="list-group-item d-flex justify-content-between align-items-center report-link">
    <a href="{entry}/index.html" class="text-decoration-none">{pretty_time}</a>
    {badge}
  </li>
'''

html += """    </ul>
        <p class="text-muted mt-4 text-center">Generated by GitHub Actions</p>
    </div>
</body>
</html>
"""

with open(index_file_path, "w") as f:
    f.write(html)

print(f"[✓] Enhanced index.html written to {index_file_path}")
