import os
import json
from datetime import datetime

REPORTS_DIR = "docs"
index_file_path = os.path.join(REPORTS_DIR, "index.html")

entries = [
    d for d in os.listdir(REPORTS_DIR)
    if os.path.isdir(os.path.join(REPORTS_DIR, d)) and d.startswith("202")
]
entries.sort(reverse=True)


html = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Allure Report Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; }
        .container { max-width: 800px; }
        .report-link:hover { background-color: #e2e6ea; }
        .badge-space { margin-left: 10px; }
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="text-center mb-3">
            <img src="https://upload.wikimedia.org/wikipedia/en/b/b0/Crypto.com_logo.svg" width="800" style="margin-bottom: 10px;">
        </div>
        <h1 class="mb-4 text-center">Available Test Reports</h1>
        <ul class="list-group">
"""


for i, entry in enumerate(entries):
    dt = datetime.strptime(entry, "%Y%m%d_%H%M%S")
    pretty_time = dt.strftime("%Y-%m-%d %H:%M")
    report_path = os.path.join(REPORTS_DIR, entry)
    summary_path = os.path.join(report_path, "widgets", "summary.json")

    passed = failed = total = "?"
    if os.path.exists(summary_path):
        with open(summary_path) as f:
            try:
                data = json.load(f)
                total = data.get("statistic", {}).get("total", "?")
                passed = data.get("statistic", {}).get("passed", "?")
                failed = data.get("statistic", {}).get("failed", "?")
            except:
                pass

    badge_latest = ' <span class="badge bg-success">Latest</span>' if i == 0 else ""
    badge_stats = f"""
        <span class="badge bg-secondary badge-space">Total: {total}</span>
        <span class="badge bg-success badge-space">Passed: {passed}</span>
        <span class="badge bg-danger badge-space">Failed: {failed}</span>
    """

    html += f'''  <li class="list-group-item d-flex justify-content-between align-items-center report-link">
    <a href="{entry}/index.html" class="text-decoration-none">{pretty_time}</a>
    <div>{badge_stats}{badge_latest}</div>
  </li>
'''

html += """    </ul>
        <p class="text-muted mt-4 text-center">Generated by GitHub Actions</p>
    </div>
</body>
</html>
"""

with open(index_file_path, "w") as f:
    f.write(html)

print(f"[✓] Enhanced index.html with stats written to {index_file_path}")
